### PR TITLE
Adding reverse proxies

### PR DESCRIPTION
**Pull request by dragonsahead**
Adding examples for several reverse proxies. Maybe we can @walterl 's https://github.com/metabase/reverse_proxy here as well

### CODE REVIEW

**Comment by walterl** [comment]
I have no problem with moving metabase/reverse_proxy in here. One less repo, and all reverse proxies together. :+1:

**Review by walterl — COMMENTED** [review]
I'd expect that the most common use case would be that, when testing a feature or reproducing a bug, someone would simply need a reverse proxy, sometimes a specific one. I'm sure being able to run all reverse proxies in a single setup will have a use case or two, but don't you think it'll be more useful to be able to run them separately?

**Comment by dragonsahead** [comment]
Sure @walterl ! I made the compose file like that as a draft, but it can be tailored. I'll cut it into 3 separate cases

**Review by walterl — APPROVED** [review]
I haven't configured Envoy or HAProxy before, but a cursory read of the configs doesn't ring any alarm bells. If you're unsure, feel free to ask someone with the relevant experience to review. :slightly_smiling_face:

**Pull request merged**
