### PR TITLE
Add HA stack

### PR DESCRIPTION
**Pull request by dragonsahead**

### CODE REVIEW

**Review by camsaul — CHANGES_REQUESTED** [review]
I'm not sure I understand what I'm looking at. What this is for, why would we want to use it, how to start it, etc. Can you add documentation for it? Just a little section in the README would be sufficient

**Comment by dragonsahead** [comment]
Sorry about that, I just added some comments :)

**Comment by dragonsahead** [comment]
My re-review request is not working @camsaul , unknown reasons :(

**Review by camsaul — APPROVED** [review]
Works for me I guess

**Pull request merged**
